# see https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/go?view=azure-devops

pool:
  vmImage: 'ubuntu-16.04' # examples of other options: 'macOS-10.14'

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.12.1' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code

steps:
- script: |
    mkdir -p '$(GOBIN)'
    mkdir -p '$(GOPATH)/pkg'
    mkdir -p '$(modulePath)'
    shopt -s extglob
    mv !(gopath) '$(modulePath)'
    echo '##vso[task.prependpath]$(GOBIN)'
    echo '##vso[task.prependpath]$(GOROOT)/bin'
  displayName: 'Set up the Go workspace'

- script: |
    go build -v -o '$(Build.ArtifactStagingDirectory)'/'$(modulePath)'-linux-amd64 .
    env GOOS=darwin GOARCH=amd64 go build -o '$(Build.ArtifactStagingDirectory)'/'$(modulePath)'-darwin-amd64 .
  workingDirectory: '$(modulePath)'
  displayName: 'Build'

# GitHub Release
# Create, edit, or delete a GitHub release.
- task: GitHubRelease@0
  inputs:
    gitHubConnection: clelange
    repositoryName: '$(Build.Repository.Name)'
    action: 'create' # Options: create, edit, delete
    target: '$(Build.SourceVersion)' # Required when action == Create || Action == Edit
    tagSource: 'manual' # Required when action == Create# Options: auto, manual
    tag: $(Build.BuildNumber) # Required when action == Edit || Action == Delete || TagSource == Manual
    #title: # Optional
    #releaseNotesSource: 'file' # Optional. Options: file, input
    #releaseNotesFile: # Optional
    #releaseNotes: # Optional
    assets: '$(Build.ArtifactStagingDirectory)/*' # Optional
    assetUploadMode: 'delete' # Optional. Options: delete, replace
    #isDraft: false # Optional
    #isPreRelease: false # Optional
    addChangeLog: true # Optional